version: '2.3'
# we should use 2.3 (because `runtime` parameter doesn't support it in v3)
# https://github.com/docker/compose/issues/5360#issuecomment-354354667

services:
  ai:
    build: .
#    command: /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --allow-root --ip='*' --port=8888 --no-browser
    ports:
      - "8888:8888"
    volumes:
      - .:/opt/notebooks/
      - /var/datasets/:/var/datasets/
      # we would store checkpoints and event files here
      - /var/models/:/var/models/
    runtime: nvidia
#    user: ${CURRENT_UID}

  tfboard:
    build:
      context: .
      dockerfile: Dockerfile-tfboard

    ports:
      - "6006:6006"

    environment:
      - LOGS_PATH=/var/models/

    volumes:
      - /var/models/:/var/models/
